import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NavBar from "@/components/NaveBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin dashbord",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          
          <div>{children}</div>
          </main>
        <Toaster />
        </body>
    </html>
  );
}
